# Generated by Django 6.0.5 on 2026-05-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Introduce el nombre descriptivo del evento universitario.', max_length=100, verbose_name='Nombre del Evento')),
                ('organizador', models.CharField(help_text='Facultad, semillero, grupo estudiantil o dependencia organizadora.', max_length=100, verbose_name='Organizador')),
                ('fecha', models.DateField(help_text='Fecha programada para la realización del evento.', verbose_name='Fecha del Evento')),
                ('cupos', models.IntegerField(help_text='Número máximo de personas permitidas para asistir.', verbose_name='Cupos Totales')),
                ('inscritos', models.IntegerField(help_text='Número de personas registradas hasta el momento.', verbose_name='Inscritos')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha'],
            },
        ),
    ]
