# Generated by Django 6.0.5 on 2026-06-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
